language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

addons:
  code_climate:
    repo_token: cd8e91b3ab72ec69225a65c03b35513fbfa8b58fadf3cf6e08852cb3f024f8ba

after_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
  - grunt coverage
  - cat coverage/lcov.info | codeclimate
